export type Sex = 'male' | 'female' | 'all';
export type AgeRange = '18-29' | '30-39' | '40-49' | '50-59' | '60-69' | '70+';

// Extended sex type for UI selection (includes all options users can choose)
export type ExtendedSex = 'male' | 'female' | 'intersex' | 'prefer-not-to-say';

export interface ReferenceRange {
  marker: string;
  sex: Sex;
  ageRange: AgeRange;
  low: number;
  typical: number;
  high: number;
  unit: string;
  sources: string[];
}

// Simple reference range for basic lookups (backward compatibility)
export interface SimpleReferenceRange {
  low: number;
  high: number;
}

export const REFERENCE_RANGES: ReferenceRange[] = [
  {
    marker: 'WBC',
    sex: 'all',
    ageRange: '18-29',
    low: 4.5,
    typical: 7.0,
    high: 11.0,
    unit: '×10⁹/L',
    sources: ['NHS', 'Mayo Clinic'],
  },
  {
    marker: 'WBC',
    sex: 'all',
    ageRange: '30-39',
    low: 4.5,
    typical: 7.0,
    high: 11.0,
    unit: '×10⁹/L',
    sources: ['NHS', 'Mayo Clinic'],
  },
  {
    marker: 'WBC',
    sex: 'all',
    ageRange: '40-49',
    low: 4.5,
    typical: 7.0,
    high: 11.0,
    unit: '×10⁹/L',
    sources: ['NHS', 'Mayo Clinic'],
  },
  {
    marker: 'WBC',
    sex: 'all',
    ageRange: '50-59',
    low: 4.5,
    typical: 7.0,
    high: 11.0,
    unit: '×10⁹/L',
    sources: ['NHS', 'Mayo Clinic'],
  },
  {
    marker: 'WBC',
    sex: 'all',
    ageRange: '60-69',
    low: 4.0,
    typical: 6.5,
    high: 11.0,
    unit: '×10⁹/L',
    sources: ['NHS', 'Mayo Clinic'],
  },
  {
    marker: 'WBC',
    sex: 'all',
    ageRange: '70+',
    low: 3.5,
    typical: 6.0,
    high: 10.5,
    unit: '×10⁹/L',
    sources: ['NHS', 'Mayo Clinic'],
  },
  {
    marker: 'RBC',
    sex: 'male',
    ageRange: '18-29',
    low: 4.7,
    typical: 5.4,
    high: 6.1,
    unit: '×10¹²/L',
    sources: ['Mayo Clinic', 'Cleveland Clinic'],
  },
  {
    marker: 'RBC',
    sex: 'male',
    ageRange: '30-39',
    low: 4.7,
    typical: 5.4,
    high: 6.1,
    unit: '×10¹²/L',
    sources: ['Mayo Clinic', 'Cleveland Clinic'],
  },
  {
    marker: 'RBC',
    sex: 'male',
    ageRange: '40-49',
    low: 4.7,
    typical: 5.4,
    high: 6.1,
    unit: '×10¹²/L',
    sources: ['Mayo Clinic', 'Cleveland Clinic'],
  },
  {
    marker: 'RBC',
    sex: 'male',
    ageRange: '50-59',
    low: 4.5,
    typical: 5.2,
    high: 6.0,
    unit: '×10¹²/L',
    sources: ['Mayo Clinic', 'Cleveland Clinic'],
  },
  {
    marker: 'RBC',
    sex: 'male',
    ageRange: '60-69',
    low: 4.3,
    typical: 5.0,
    high: 5.9,
    unit: '×10¹²/L',
    sources: ['Mayo Clinic', 'Cleveland Clinic'],
  },
  {
    marker: 'RBC',
    sex: 'male',
    ageRange: '70+',
    low: 4.0,
    typical: 4.8,
    high: 5.7,
    unit: '×10¹²/L',
    sources: ['Mayo Clinic', 'Cleveland Clinic'],
  },
  {
    marker: 'RBC',
    sex: 'female',
    ageRange: '18-29',
    low: 4.2,
    typical: 4.8,
    high: 5.4,
    unit: '×10¹²/L',
    sources: ['Mayo Clinic', 'Cleveland Clinic'],
  },
  {
    marker: 'RBC',
    sex: 'female',
    ageRange: '30-39',
    low: 4.2,
    typical: 4.8,
    high: 5.4,
    unit: '×10¹²/L',
    sources: ['Mayo Clinic', 'Cleveland Clinic'],
  },
  {
    marker: 'RBC',
    sex: 'female',
    ageRange: '40-49',
    low: 4.2,
    typical: 4.8,
    high: 5.4,
    unit: '×10¹²/L',
    sources: ['Mayo Clinic', 'Cleveland Clinic'],
  },
  {
    marker: 'RBC',
    sex: 'female',
    ageRange: '50-59',
    low: 4.0,
    typical: 4.6,
    high: 5.3,
    unit: '×10¹²/L',
    sources: ['Mayo Clinic', 'Cleveland Clinic'],
  },
  {
    marker: 'RBC',
    sex: 'female',
    ageRange: '60-69',
    low: 4.0,
    typical: 4.6,
    high: 5.3,
    unit: '×10¹²/L',
    sources: ['Mayo Clinic', 'Cleveland Clinic'],
  },
  {
    marker: 'RBC',
    sex: 'female',
    ageRange: '70+',
    low: 3.8,
    typical: 4.4,
    high: 5.1,
    unit: '×10¹²/L',
    sources: ['Mayo Clinic', 'Cleveland Clinic'],
  },
  {
    marker: 'HGB',
    sex: 'male',
    ageRange: '18-29',
    low: 13.8,
    typical: 15.5,
    high: 17.2,
    unit: 'g/dL',
    sources: ['NHS', 'Mayo Clinic'],
  },
  {
    marker: 'HGB',
    sex: 'male',
    ageRange: '30-39',
    low: 13.8,
    typical: 15.5,
    high: 17.2,
    unit: 'g/dL',
    sources: ['NHS', 'Mayo Clinic'],
  },
  {
    marker: 'HGB',
    sex: 'male',
    ageRange: '40-49',
    low: 13.8,
    typical: 15.5,
    high: 17.2,
    unit: 'g/dL',
    sources: ['NHS', 'Mayo Clinic'],
  },
  {
    marker: 'HGB',
    sex: 'male',
    ageRange: '50-59',
    low: 13.5,
    typical: 15.2,
    high: 17.0,
    unit: 'g/dL',
    sources: ['NHS', 'Mayo Clinic'],
  },
  {
    marker: 'HGB',
    sex: 'male',
    ageRange: '60-69',
    low: 13.2,
    typical: 15.0,
    high: 16.8,
    unit: 'g/dL',
    sources: ['NHS', 'Mayo Clinic'],
  },
  {
    marker: 'HGB',
    sex: 'male',
    ageRange: '70+',
    low: 12.8,
    typical: 14.5,
    high: 16.5,
    unit: 'g/dL',
    sources: ['NHS', 'Mayo Clinic'],
  },
  {
    marker: 'HGB',
    sex: 'female',
    ageRange: '18-29',
    low: 12.0,
    typical: 13.9,
    high: 15.5,
    unit: 'g/dL',
    sources: ['NHS', 'Mayo Clinic'],
  },
  {
    marker: 'HGB',
    sex: 'female',
    ageRange: '30-39',
    low: 12.0,
    typical: 13.9,
    high: 15.5,
    unit: 'g/dL',
    sources: ['NHS', 'Mayo Clinic'],
  },
  {
    marker: 'HGB',
    sex: 'female',
    ageRange: '40-49',
    low: 12.0,
    typical: 13.9,
    high: 15.5,
    unit: 'g/dL',
    sources: ['NHS', 'Mayo Clinic'],
  },
  {
    marker: 'HGB',
    sex: 'female',
    ageRange: '50-59',
    low: 11.8,
    typical: 13.7,
    high: 15.3,
    unit: 'g/dL',
    sources: ['NHS', 'Mayo Clinic'],
  },
  {
    marker: 'HGB',
    sex: 'female',
    ageRange: '60-69',
    low: 11.8,
    typical: 13.7,
    high: 15.3,
    unit: 'g/dL',
    sources: ['NHS', 'Mayo Clinic'],
  },
  {
    marker: 'HGB',
    sex: 'female',
    ageRange: '70+',
    low: 11.5,
    typical: 13.4,
    high: 15.0,
    unit: 'g/dL',
    sources: ['NHS', 'Mayo Clinic'],
  },
  {
    marker: 'HCT',
    sex: 'male',
    ageRange: '18-29',
    low: 40.7,
    typical: 45.5,
    high: 50.3,
    unit: '%',
    sources: ['Mayo Clinic', 'LabCorp'],
  },
  {
    marker: 'HCT',
    sex: 'male',
    ageRange: '30-39',
    low: 40.7,
    typical: 45.5,
    high: 50.3,
    unit: '%',
    sources: ['Mayo Clinic', 'LabCorp'],
  },
  {
    marker: 'HCT',
    sex: 'male',
    ageRange: '40-49',
    low: 40.7,
    typical: 45.5,
    high: 50.3,
    unit: '%',
    sources: ['Mayo Clinic', 'LabCorp'],
  },
  {
    marker: 'HCT',
    sex: 'male',
    ageRange: '50-59',
    low: 39.0,
    typical: 44.0,
    high: 50.0,
    unit: '%',
    sources: ['Mayo Clinic', 'LabCorp'],
  },
  {
    marker: 'HCT',
    sex: 'male',
    ageRange: '60-69',
    low: 38.0,
    typical: 43.5,
    high: 49.0,
    unit: '%',
    sources: ['Mayo Clinic', 'LabCorp'],
  },
  {
    marker: 'HCT',
    sex: 'male',
    ageRange: '70+',
    low: 37.0,
    typical: 42.5,
    high: 48.0,
    unit: '%',
    sources: ['Mayo Clinic', 'LabCorp'],
  },
  {
    marker: 'HCT',
    sex: 'female',
    ageRange: '18-29',
    low: 36.1,
    typical: 40.5,
    high: 44.9,
    unit: '%',
    sources: ['Mayo Clinic', 'LabCorp'],
  },
  {
    marker: 'HCT',
    sex: 'female',
    ageRange: '30-39',
    low: 36.1,
    typical: 40.5,
    high: 44.9,
    unit: '%',
    sources: ['Mayo Clinic', 'LabCorp'],
  },
  {
    marker: 'HCT',
    sex: 'female',
    ageRange: '40-49',
    low: 36.1,
    typical: 40.5,
    high: 44.9,
    unit: '%',
    sources: ['Mayo Clinic', 'LabCorp'],
  },
  {
    marker: 'HCT',
    sex: 'female',
    ageRange: '50-59',
    low: 35.0,
    typical: 39.5,
    high: 44.0,
    unit: '%',
    sources: ['Mayo Clinic', 'LabCorp'],
  },
  {
    marker: 'HCT',
    sex: 'female',
    ageRange: '60-69',
    low: 35.0,
    typical: 39.5,
    high: 44.0,
    unit: '%',
    sources: ['Mayo Clinic', 'LabCorp'],
  },
  {
    marker: 'HCT',
    sex: 'female',
    ageRange: '70+',
    low: 34.0,
    typical: 39.0,
    high: 43.5,
    unit: '%',
    sources: ['Mayo Clinic', 'LabCorp'],
  },
  {
    marker: 'PLT',
    sex: 'all',
    ageRange: '18-29',
    low: 150,
    typical: 275,
    high: 400,
    unit: '×10⁹/L',
    sources: ['NHS', 'Mayo Clinic'],
  },
  {
    marker: 'PLT',
    sex: 'all',
    ageRange: '30-39',
    low: 150,
    typical: 275,
    high: 400,
    unit: '×10⁹/L',
    sources: ['NHS', 'Mayo Clinic'],
  },
  {
    marker: 'PLT',
    sex: 'all',
    ageRange: '40-49',
    low: 150,
    typical: 275,
    high: 400,
    unit: '×10⁹/L',
    sources: ['NHS', 'Mayo Clinic'],
  },
  {
    marker: 'PLT',
    sex: 'all',
    ageRange: '50-59',
    low: 150,
    typical: 275,
    high: 400,
    unit: '×10⁹/L',
    sources: ['NHS', 'Mayo Clinic'],
  },
  {
    marker: 'PLT',
    sex: 'all',
    ageRange: '60-69',
    low: 150,
    typical: 275,
    high: 400,
    unit: '×10⁹/L',
    sources: ['NHS', 'Mayo Clinic'],
  },
  {
    marker: 'PLT',
    sex: 'all',
    ageRange: '70+',
    low: 130,
    typical: 265,
    high: 400,
    unit: '×10⁹/L',
    sources: ['NHS', 'Mayo Clinic'],
  },
  {
    marker: 'MCV',
    sex: 'all',
    ageRange: '18-29',
    low: 80,
    typical: 90,
    high: 100,
    unit: 'fL',
    sources: ['NHS', 'Cleveland Clinic'],
  },
  {
    marker: 'MCV',
    sex: 'all',
    ageRange: '30-39',
    low: 80,
    typical: 90,
    high: 100,
    unit: 'fL',
    sources: ['NHS', 'Cleveland Clinic'],
  },
  {
    marker: 'MCV',
    sex: 'all',
    ageRange: '40-49',
    low: 80,
    typical: 90,
    high: 100,
    unit: 'fL',
    sources: ['NHS', 'Cleveland Clinic'],
  },
  {
    marker: 'MCV',
    sex: 'all',
    ageRange: '50-59',
    low: 80,
    typical: 90,
    high: 100,
    unit: 'fL',
    sources: ['NHS', 'Cleveland Clinic'],
  },
  {
    marker: 'MCV',
    sex: 'all',
    ageRange: '60-69',
    low: 80,
    typical: 90,
    high: 100,
    unit: 'fL',
    sources: ['NHS', 'Cleveland Clinic'],
  },
  {
    marker: 'MCV',
    sex: 'all',
    ageRange: '70+',
    low: 80,
    typical: 90,
    high: 100,
    unit: 'fL',
    sources: ['NHS', 'Cleveland Clinic'],
  },
  {
    marker: 'MCH',
    sex: 'all',
    ageRange: '18-29',
    low: 27,
    typical: 30,
    high: 33,
    unit: 'pg',
    sources: ['Mayo Clinic', 'LabCorp'],
  },
  {
    marker: 'MCH',
    sex: 'all',
    ageRange: '30-39',
    low: 27,
    typical: 30,
    high: 33,
    unit: 'pg',
    sources: ['Mayo Clinic', 'LabCorp'],
  },
  {
    marker: 'MCH',
    sex: 'all',
    ageRange: '40-49',
    low: 27,
    typical: 30,
    high: 33,
    unit: 'pg',
    sources: ['Mayo Clinic', 'LabCorp'],
  },
  {
    marker: 'MCH',
    sex: 'all',
    ageRange: '50-59',
    low: 27,
    typical: 30,
    high: 33,
    unit: 'pg',
    sources: ['Mayo Clinic', 'LabCorp'],
  },
  {
    marker: 'MCH',
    sex: 'all',
    ageRange: '60-69',
    low: 27,
    typical: 30,
    high: 33,
    unit: 'pg',
    sources: ['Mayo Clinic', 'LabCorp'],
  },
  {
    marker: 'MCH',
    sex: 'all',
    ageRange: '70+',
    low: 27,
    typical: 30,
    high: 33,
    unit: 'pg',
    sources: ['Mayo Clinic', 'LabCorp'],
  },
  {
    marker: 'MCHC',
    sex: 'all',
    ageRange: '18-29',
    low: 32,
    typical: 34,
    high: 36,
    unit: 'g/dL',
    sources: ['Mayo Clinic', 'Quest'],
  },
  {
    marker: 'MCHC',
    sex: 'all',
    ageRange: '30-39',
    low: 32,
    typical: 34,
    high: 36,
    unit: 'g/dL',
    sources: ['Mayo Clinic', 'Quest'],
  },
  {
    marker: 'MCHC',
    sex: 'all',
    ageRange: '40-49',
    low: 32,
    typical: 34,
    high: 36,
    unit: 'g/dL',
    sources: ['Mayo Clinic', 'Quest'],
  },
  {
    marker: 'MCHC',
    sex: 'all',
    ageRange: '50-59',
    low: 32,
    typical: 34,
    high: 36,
    unit: 'g/dL',
    sources: ['Mayo Clinic', 'Quest'],
  },
  {
    marker: 'MCHC',
    sex: 'all',
    ageRange: '60-69',
    low: 32,
    typical: 34,
    high: 36,
    unit: 'g/dL',
    sources: ['Mayo Clinic', 'Quest'],
  },
  {
    marker: 'MCHC',
    sex: 'all',
    ageRange: '70+',
    low: 32,
    typical: 34,
    high: 36,
    unit: 'g/dL',
    sources: ['Mayo Clinic', 'Quest'],
  },
  {
    marker: 'RDW',
    sex: 'all',
    ageRange: '18-29',
    low: 11.5,
    typical: 13.0,
    high: 14.5,
    unit: '%',
    sources: ['Cleveland Clinic', 'LabCorp'],
  },
  {
    marker: 'RDW',
    sex: 'all',
    ageRange: '30-39',
    low: 11.5,
    typical: 13.0,
    high: 14.5,
    unit: '%',
    sources: ['Cleveland Clinic', 'LabCorp'],
  },
  {
    marker: 'RDW',
    sex: 'all',
    ageRange: '40-49',
    low: 11.5,
    typical: 13.0,
    high: 14.5,
    unit: '%',
    sources: ['Cleveland Clinic', 'LabCorp'],
  },
  {
    marker: 'RDW',
    sex: 'all',
    ageRange: '50-59',
    low: 11.5,
    typical: 13.0,
    high: 14.5,
    unit: '%',
    sources: ['Cleveland Clinic', 'LabCorp'],
  },
  {
    marker: 'RDW',
    sex: 'all',
    ageRange: '60-69',
    low: 11.5,
    typical: 13.0,
    high: 14.5,
    unit: '%',
    sources: ['Cleveland Clinic', 'LabCorp'],
  },
  {
    marker: 'RDW',
    sex: 'all',
    ageRange: '70+',
    low: 11.5,
    typical: 13.5,
    high: 15.0,
    unit: '%',
    sources: ['Cleveland Clinic', 'LabCorp'],
  },
  {
    marker: 'MPV',
    sex: 'all',
    ageRange: '18-29',
    low: 7.5,
    typical: 9.5,
    high: 11.5,
    unit: 'fL',
    sources: ['Quest', 'LabCorp'],
  },
  {
    marker: 'MPV',
    sex: 'all',
    ageRange: '30-39',
    low: 7.5,
    typical: 9.5,
    high: 11.5,
    unit: 'fL',
    sources: ['Quest', 'LabCorp'],
  },
  {
    marker: 'MPV',
    sex: 'all',
    ageRange: '40-49',
    low: 7.5,
    typical: 9.5,
    high: 11.5,
    unit: 'fL',
    sources: ['Quest', 'LabCorp'],
  },
  {
    marker: 'MPV',
    sex: 'all',
    ageRange: '50-59',
    low: 7.5,
    typical: 9.5,
    high: 11.5,
    unit: 'fL',
    sources: ['Quest', 'LabCorp'],
  },
  {
    marker: 'MPV',
    sex: 'all',
    ageRange: '60-69',
    low: 7.5,
    typical: 9.5,
    high: 11.5,
    unit: 'fL',
    sources: ['Quest', 'LabCorp'],
  },
  {
    marker: 'MPV',
    sex: 'all',
    ageRange: '70+',
    low: 7.5,
    typical: 9.5,
    high: 11.5,
    unit: 'fL',
    sources: ['Quest', 'LabCorp'],
  },
  {
    marker: 'NEUT',
    sex: 'all',
    ageRange: '18-29',
    low: 2.0,
    typical: 4.5,
    high: 7.5,
    unit: '×10⁹/L',
    sources: ['NHS', 'Mayo Clinic'],
  },
  {
    marker: 'NEUT',
    sex: 'all',
    ageRange: '30-39',
    low: 2.0,
    typical: 4.5,
    high: 7.5,
    unit: '×10⁹/L',
    sources: ['NHS', 'Mayo Clinic'],
  },
  {
    marker: 'NEUT',
    sex: 'all',
    ageRange: '40-49',
    low: 2.0,
    typical: 4.5,
    high: 7.5,
    unit: '×10⁹/L',
    sources: ['NHS', 'Mayo Clinic'],
  },
  {
    marker: 'NEUT',
    sex: 'all',
    ageRange: '50-59',
    low: 2.0,
    typical: 4.5,
    high: 7.5,
    unit: '×10⁹/L',
    sources: ['NHS', 'Mayo Clinic'],
  },
  {
    marker: 'NEUT',
    sex: 'all',
    ageRange: '60-69',
    low: 2.0,
    typical: 4.5,
    high: 7.5,
    unit: '×10⁹/L',
    sources: ['NHS', 'Mayo Clinic'],
  },
  {
    marker: 'NEUT',
    sex: 'all',
    ageRange: '70+',
    low: 1.8,
    typical: 4.2,
    high: 7.5,
    unit: '×10⁹/L',
    sources: ['NHS', 'Mayo Clinic'],
  },
  {
    marker: 'LYMPH',
    sex: 'all',
    ageRange: '18-29',
    low: 1.0,
    typical: 2.0,
    high: 4.0,
    unit: '×10⁹/L',
    sources: ['NHS', 'Cleveland Clinic'],
  },
  {
    marker: 'LYMPH',
    sex: 'all',
    ageRange: '30-39',
    low: 1.0,
    typical: 2.0,
    high: 4.0,
    unit: '×10⁹/L',
    sources: ['NHS', 'Cleveland Clinic'],
  },
  {
    marker: 'LYMPH',
    sex: 'all',
    ageRange: '40-49',
    low: 1.0,
    typical: 2.0,
    high: 4.0,
    unit: '×10⁹/L',
    sources: ['NHS', 'Cleveland Clinic'],
  },
  {
    marker: 'LYMPH',
    sex: 'all',
    ageRange: '50-59',
    low: 1.0,
    typical: 2.0,
    high: 4.0,
    unit: '×10⁹/L',
    sources: ['NHS', 'Cleveland Clinic'],
  },
  {
    marker: 'LYMPH',
    sex: 'all',
    ageRange: '60-69',
    low: 1.0,
    typical: 2.0,
    high: 4.0,
    unit: '×10⁹/L',
    sources: ['NHS', 'Cleveland Clinic'],
  },
  {
    marker: 'LYMPH',
    sex: 'all',
    ageRange: '70+',
    low: 0.8,
    typical: 1.8,
    high: 3.8,
    unit: '×10⁹/L',
    sources: ['NHS', 'Cleveland Clinic'],
  },
  {
    marker: 'MONO',
    sex: 'all',
    ageRange: '18-29',
    low: 0.2,
    typical: 0.5,
    high: 0.8,
    unit: '×10⁹/L',
    sources: ['Mayo Clinic', 'Quest'],
  },
  {
    marker: 'MONO',
    sex: 'all',
    ageRange: '30-39',
    low: 0.2,
    typical: 0.5,
    high: 0.8,
    unit: '×10⁹/L',
    sources: ['Mayo Clinic', 'Quest'],
  },
  {
    marker: 'MONO',
    sex: 'all',
    ageRange: '40-49',
    low: 0.2,
    typical: 0.5,
    high: 0.8,
    unit: '×10⁹/L',
    sources: ['Mayo Clinic', 'Quest'],
  },
  {
    marker: 'MONO',
    sex: 'all',
    ageRange: '50-59',
    low: 0.2,
    typical: 0.5,
    high: 0.8,
    unit: '×10⁹/L',
    sources: ['Mayo Clinic', 'Quest'],
  },
  {
    marker: 'MONO',
    sex: 'all',
    ageRange: '60-69',
    low: 0.2,
    typical: 0.5,
    high: 0.8,
    unit: '×10⁹/L',
    sources: ['Mayo Clinic', 'Quest'],
  },
  {
    marker: 'MONO',
    sex: 'all',
    ageRange: '70+',
    low: 0.2,
    typical: 0.5,
    high: 0.8,
    unit: '×10⁹/L',
    sources: ['Mayo Clinic', 'Quest'],
  },
  {
    marker: 'EOS',
    sex: 'all',
    ageRange: '18-29',
    low: 0.0,
    typical: 0.2,
    high: 0.5,
    unit: '×10⁹/L',
    sources: ['NHS', 'LabCorp'],
  },
  {
    marker: 'EOS',
    sex: 'all',
    ageRange: '30-39',
    low: 0.0,
    typical: 0.2,
    high: 0.5,
    unit: '×10⁹/L',
    sources: ['NHS', 'LabCorp'],
  },
  {
    marker: 'EOS',
    sex: 'all',
    ageRange: '40-49',
    low: 0.0,
    typical: 0.2,
    high: 0.5,
    unit: '×10⁹/L',
    sources: ['NHS', 'LabCorp'],
  },
  {
    marker: 'EOS',
    sex: 'all',
    ageRange: '50-59',
    low: 0.0,
    typical: 0.2,
    high: 0.5,
    unit: '×10⁹/L',
    sources: ['NHS', 'LabCorp'],
  },
  {
    marker: 'EOS',
    sex: 'all',
    ageRange: '60-69',
    low: 0.0,
    typical: 0.2,
    high: 0.5,
    unit: '×10⁹/L',
    sources: ['NHS', 'LabCorp'],
  },
  {
    marker: 'EOS',
    sex: 'all',
    ageRange: '70+',
    low: 0.0,
    typical: 0.2,
    high: 0.5,
    unit: '×10⁹/L',
    sources: ['NHS', 'LabCorp'],
  },
  {
    marker: 'BASO',
    sex: 'all',
    ageRange: '18-29',
    low: 0.0,
    typical: 0.05,
    high: 0.2,
    unit: '×10⁹/L',
    sources: ['Mayo Clinic', 'Cleveland Clinic'],
  },
  {
    marker: 'BASO',
    sex: 'all',
    ageRange: '30-39',
    low: 0.0,
    typical: 0.05,
    high: 0.2,
    unit: '×10⁹/L',
    sources: ['Mayo Clinic', 'Cleveland Clinic'],
  },
  {
    marker: 'BASO',
    sex: 'all',
    ageRange: '40-49',
    low: 0.0,
    typical: 0.05,
    high: 0.2,
    unit: '×10⁹/L',
    sources: ['Mayo Clinic', 'Cleveland Clinic'],
  },
  {
    marker: 'BASO',
    sex: 'all',
    ageRange: '50-59',
    low: 0.0,
    typical: 0.05,
    high: 0.2,
    unit: '×10⁹/L',
    sources: ['Mayo Clinic', 'Cleveland Clinic'],
  },
  {
    marker: 'BASO',
    sex: 'all',
    ageRange: '60-69',
    low: 0.0,
    typical: 0.05,
    high: 0.2,
    unit: '×10⁹/L',
    sources: ['Mayo Clinic', 'Cleveland Clinic'],
  },
  {
    marker: 'BASO',
    sex: 'all',
    ageRange: '70+',
    low: 0.0,
    typical: 0.05,
    high: 0.2,
    unit: '×10⁹/L',
    sources: ['Mayo Clinic', 'Cleveland Clinic'],
  },
];

/**
 * Get full reference range with metadata for a specific marker, sex, and age range
 *
 * See /reference/SOURCES.md for data sources and methodology.
 *
 * @param marker - The marker name (e.g., 'WBC', 'HGB')
 * @param sex - The sex category (supports all 4 UI options)
 * @param ageRange - The age range
 * @returns Full reference range with sources and metadata, or null if not available
 */
export function getReferenceRange(
  marker: string,
  sex: ExtendedSex,
  ageRange: AgeRange
): ReferenceRange | null {
  const normalizedSex = sex === 'prefer-not-to-say' || sex === 'intersex' ? 'all' : sex;

  let match = REFERENCE_RANGES.find(
    (range) =>
      range.marker === marker &&
      range.sex === normalizedSex &&
      range.ageRange === ageRange
  );

  if (!match && normalizedSex !== 'all') {
    match = REFERENCE_RANGES.find(
      (range) =>
        range.marker === marker &&
        range.sex === 'all' &&
        range.ageRange === ageRange
    );
  }

  return match || null;
}

/**
 * Get simple reference range (low/high only) for a specific marker, sex, and age range
 *
 * This is a lightweight version that returns only the range bounds without metadata.
 * Use this for basic validation or simple range checks.
 *
 * @param marker - The marker name (e.g., 'WBC', 'HGB')
 * @param sex - The sex category (supports all 4 UI options)
 * @param ageRange - The age range
 * @returns Simple reference range with just low/high, or null if not available
 */
export function getSimpleReferenceRange(
  marker: string,
  sex: ExtendedSex,
  ageRange: AgeRange
): SimpleReferenceRange | null {
  const fullRange = getReferenceRange(marker, sex, ageRange);
  if (!fullRange) return null;

  return {
    low: fullRange.low,
    high: fullRange.high,
  };
}
